/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsOrchestratorRouteImport } from './routes/agents.orchestrator'
import { Route as AgentsDeviceRouteImport } from './routes/agents.device'
import { Route as AgentsBehaviorRouteImport } from './routes/agents.behavior'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsOrchestratorRoute = AgentsOrchestratorRouteImport.update({
  id: '/agents/orchestrator',
  path: '/agents/orchestrator',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDeviceRoute = AgentsDeviceRouteImport.update({
  id: '/agents/device',
  path: '/agents/device',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsBehaviorRoute = AgentsBehaviorRouteImport.update({
  id: '/agents/behavior',
  path: '/agents/behavior',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents/behavior': typeof AgentsBehaviorRoute
  '/agents/device': typeof AgentsDeviceRoute
  '/agents/orchestrator': typeof AgentsOrchestratorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/progress': typeof ProgressRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agents/behavior': typeof AgentsBehaviorRoute
  '/agents/device': typeof AgentsDeviceRoute
  '/agents/orchestrator': typeof AgentsOrchestratorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/agents/behavior': typeof AgentsBehaviorRoute
  '/agents/device': typeof AgentsDeviceRoute
  '/agents/orchestrator': typeof AgentsOrchestratorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/progress'
    | '/admin'
    | '/agents/behavior'
    | '/agents/device'
    | '/agents/orchestrator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/progress'
    | '/admin'
    | '/agents/behavior'
    | '/agents/device'
    | '/agents/orchestrator'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/progress'
    | '/_authenticated/admin'
    | '/agents/behavior'
    | '/agents/device'
    | '/agents/orchestrator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProgressRoute: typeof ProgressRoute
  AgentsBehaviorRoute: typeof AgentsBehaviorRoute
  AgentsDeviceRoute: typeof AgentsDeviceRoute
  AgentsOrchestratorRoute: typeof AgentsOrchestratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/orchestrator': {
      id: '/agents/orchestrator'
      path: '/agents/orchestrator'
      fullPath: '/agents/orchestrator'
      preLoaderRoute: typeof AgentsOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/device': {
      id: '/agents/device'
      path: '/agents/device'
      fullPath: '/agents/device'
      preLoaderRoute: typeof AgentsDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/behavior': {
      id: '/agents/behavior'
      path: '/agents/behavior'
      fullPath: '/agents/behavior'
      preLoaderRoute: typeof AgentsBehaviorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ProgressRoute: ProgressRoute,
  AgentsBehaviorRoute: AgentsBehaviorRoute,
  AgentsDeviceRoute: AgentsDeviceRoute,
  AgentsOrchestratorRoute: AgentsOrchestratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
